SUPL_HOST=supl.google.com
SUPL_PORT=7275
SUPL_VER=0x20000
SUPL_MODE=1
SUPL_ES=1
NTP_SERVER=pool.ntp.org
XTRA_SERVER_1=http://xtrapath1.izatcloud.net/xtra2.bin
XTRA_SERVER_2=http://xtrapath2.izatcloud.net/xtra2.bin
XTRA_SERVER_3=http://xtrapath3.izatcloud.net/xtra2.bin
LPP_PROFILE=3
A_GLONASS_POS_PROTOCOL_SELECT=0
INTERMEDIATE_POS=0
ACCURACY_THRES=0
DEFAULT_AGPS_ENABLE=TRUE
REPORT_POSITION_USE_SUPL_IF_UNKNOWN=1
USE_EMERGENCY_PDN_FOR_EMERGENCY_SUPL=1
ENABLE_WIPER=0
DW_DAYS=3
